---
- name: Ejecutar el rol TP_INI y otra tarea
  hosts:
    - testing
    - produccion

  become: yes  #Super Previlegios
  
  vars_files:
    - vars/main.yml  # Carga las variables definidas en vars/main.yml

  tasks:
    - name: Incluir el rol TP_INI
      include_role:
        name: TP_INI

    - name: Alta usuarios
      include_role:
        name: Alta_Usuarios_Barboza

    - name: Sudoers
      include_role:
        name: Sudoers_Barboza

    - name: Instala tools
      include_role:
        name: Instala-tools_Barboza



